server.port: 8082

spring:
  application:
    name: config-service
  data:
    redis:
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/apzda_config_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.apzda: debug

